### PR TITLE
Updated namespace names to reflect changes in the standard library

### PR DESCRIPTION
**Pull request by bendykst**

### CODE REVIEW

**Comment by crackofdusk** [comment]
I would rather switch to the new `io` API.

**Comment by bendykst** [comment]
There is more that needs to be updated before the project will compile and it will be difficult to switch to the new API without being able to to compile the code. I recommend temporarily using `old_io` until the project compiles and then switching to the new API.

**Comment by crackofdusk** [comment]
Sure thing. Thanks for your contributions. This project is currently on the back burner.

**Comment by crackofdusk** [comment]
Could you please rebase this so that I can merge it easily?

**Comment by bendykst** [comment]
Sure

**Comment by bendykst** [comment]
Ok, I think it's ready to go.

**Pull request merged**
